### ISSUE TITLE
Grid

### ISSUE THREAD

**Issue by myscreen** [yasevich/endless-recycler-view#11]
Hi, I would like to have progressview with span size of 1 when my grid layout has 3 column. I attempted to use this code but it is not impossible. Please help me to resolve it.

```
gridLayoutManager.setSpanSizeLookup(new GridLayoutManager.SpanSizeLookup() {
            @Override
            public int getSpanSize(int position) {
                return adapter.isHeader(position) ? gridLayoutManager.getSpanCount() : 1;
            }
 });
```

and 

```
gridLayoutManager.setSpanSizeLookup(new GridLayoutManager.SpanSizeLookup() {
            @Override
            public int getSpanSize(int position) {
 switch(adapter.getItemViewType(position)){
                    case adapter.TYPE_HEADER:
                        return 1;
                    case adapter.TYPE_ITEM:
                        return gridLayoutManager.getSpanCount(); //number of columns of the grid
                    default:
                        return 1;
 } 
  }
 });
```

Thanks and Best Regards

**Comment by yasevich** [comment]
Hi!

Thank you for reporting this.

I'm not sure that this code must be in the library because implementations of `GridLayoutManager.SpanSizeLookup` may be complex. So it's up to a client to resolve span's size.

Here is an example of how you can do it:

``` Java
final EndlessRecyclerView list = ...
final GridLayoutManager manager = new GridLayoutManager(v.getContext(), 3);

// we want progress view to fill entire row
manager.setSpanSizeLookup(new GridLayoutManager.SpanSizeLookup() {
    @Override
    public int getSpanSize(int position) {
        return list.isRefreshing() && position == manager.getItemCount() ?
                manager.getSpanCount() : 1;
    }
});
```

**Comment by myscreen** [comment]
hi, thanks for answer but the list does not have isRefreshing() . ?!
Edit: Sorry I was using v1.0. now i found it and will inform you about result.
Thanks and Best Regards

**Comment by myscreen** [comment]
hi again, so sorry, it is not working and also new version in grid mode when scrolling down 3 times, it comes back to first row, scroll up. I think it is a bug however in version 1.0 the scrolling is work nice.

At the end, this code not working for span size of loading.

**Comment by yasevich** [comment]
> it is not working and also new version in grid mode when scrolling down 3 times, it comes back to first row, scroll up

I'm going to need more details on this issue. Have you tried to run sample application on your device? Does it work the same? What device do you use? What Android version does it run?

Could you also give a snippet of how you use this view?

I'm guessing that this could happen if you replace adapter when data is being refreshed.

> At the end, this code not working for span size of loading.

Yet again, on my device the sample app that comes with the library works fine:

![Sample](http://i.imgur.com/XvUgMZY.gif)

**Comment by myscreen** [comment]
in my adapter i have also extra header.

```
 @Override
    public RecyclerView.ViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
        ctx = parent.getContext();
        if (viewType == TYPE_HEADER) {
            View view = LayoutInflater.from(parent.getContext()).inflate(R.layout.header_recyclerview_new_channels, parent, false);
            return new ChannelSliderHeaderViewHolder(view);
        } else if (viewType == TYPE_ITEM) {
            View view = LayoutInflater.from(parent.getContext()).inflate(R.layout.subscribe_layout, parent, false);
            return new ChannelViewHolder(view);
        }
        throw new RuntimeException("there is no type that matches the type " + viewType + " + make sure your using types correctly");
    }
```

and also

```
@Override
    public int getItemViewType(int position) {
        if (isPositionHeader(position))
            return TYPE_HEADER;
        return TYPE_ITEM;
    }

    private boolean isPositionHeader(int position) {
        return position == 0;
    }

    public boolean isHeader(int position){
        if(position==0){
            return true;
        } else {
            return false;
        }
    }
```

Please review and help me. thanks

**Comment by yasevich** [comment]
I don't see any logical problems here. The header itself can not be a problem.

**Comment by myscreen** [comment]
hi again 
I use this code and the result is a video that you can see.

http://www.myscreen.my/img/device-2016-03-16-channels.mp4

```
 return list.isRefreshing() && position == gridLayoutManager.getItemCount() - 1 ?
                        gridLayoutManager.getSpanCount() : 1;
```

**Comment by yasevich** [comment]
Ok. I see two problems here.

First, method `gridLayoutManager.getItemCount()` is going to return you number of items in _your_ adapter. That means you don't need to subtract 1 to get position of a progress view because it will be equals to a number of items. I had the same mistake when I posted my [first comment](https://github.com/yasevich/endless-recycler-view/issues/11#issuecomment-196476310) (I edited it later). This will give you proper span size.

Second, you need to specify progress view height explicitly in your layout file. This way it won't fill entire screen during scrolling.

However it's still a mistery to me why your list scrolls up.

**Comment by myscreen** [comment]
it works but your new version after loading it scrolls up in grid and in list the last 2 or 3 rows disappear. ;( please help

**Comment by yasevich** [comment]
How do you update the list after loading?

**Comment by myscreen** [comment]
add data to adapter then notifydatachanged then 

```
                        handler.postDelayed(new Runnable() {
                            @Override
                            public void run() {
                                list.setRefreshing(false);
                                loading = false;
                            }
                        }, DELAY);
```

**Comment by yasevich** [comment]
This doesn't give me much. In order to solve this problem I'm going to need to see more code.
