### ISSUE TITLE
new issue with com.android.support:appcompat-v7:23.2.1

### ISSUE THREAD

**Issue by myscreen** [yasevich/endless-recycler-view#12]
hi
when I update frp, 23.1.0 to 23.2.1, the loading gone and sometimes it goes to middle of page. Also after some refresh recyclerview scroll to first position. I think it is bug ;(.
Thanks

**Comment by yasevich** [comment]
This issue has been raised earlier in #11.

> when I update frp, 23.1.0 to 23.2.1, the loading gone and sometimes it goes to middle of page

See second part of this [comment](https://github.com/yasevich/endless-recycler-view/issues/11#issuecomment-196992106).

> Also after some refresh recyclerview scroll to first position. I think it is bug ;(.

I don't know why this happens. There is not enough information to reproduce this bug.

**Comment by yasevich** [comment]
This issue has been raised earlier in #11.

> when I update frp, 23.1.0 to 23.2.1, the loading gone and sometimes it goes to middle of page

See second part of this [comment](https://github.com/yasevich/endless-recycler-view/issues/11#issuecomment-196992106).

> Also after some refresh recyclerview scroll to first position. I think it is bug ;(.

I don't know why this happens. There is not enough information to reproduce this bug.
